### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by essen** [mdevilliers/erlang-mesos#6]
Hi, trying to compile this so I can include it in the erlang.mk index. I install mesos 0.22.1, I am guessing that's not compatible? I get this:

```
In file included from /usr/include/mesos/mesos.hpp:22:0,
                 from ../c_src/executor_c_api.cpp:29:
/usr/include/mesos/mesos.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/usr/include/mesos/mesos.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/usr/include/mesos/mesos.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
```

**Comment by mdevilliers** [comment]
Hey - off the top of my head what is your current version of protoc?

For me it is -

```
$ protoc --version
libprotoc 2.5.0
```

From memory I think mesos needs 2.5.0 to compile but I can't remember where I saw that.

I've tested with 0.22.0 and as far as I know there aren't any protobuffer changes in 0.22.1

Anyway - tell me how you get on?

Mark

**Comment by essen** [comment]
2.6.1 apparently.

Installed this package: https://aur.archlinux.org/packages/mesos/

**Comment by mdevilliers** [comment]
From mesos.pb.h -

```
#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif
```

which seems strangely exact? 

Is mandating 2.5 out of the question?

Failing that the .h file could be generated using something like -

```
protoc --cpp_out=. --proto_path=/usr/include/mesos/ /usr/include/mesos/mesos.proto
```

But that seems a bit weird and might have unintended consequences.

Mark

**Comment by essen** [comment]
Yes it would be difficult to find the older version, fix things, make sure other things don't break etc. though not impossible of course. But I will have to defer that to after I solve a few other projects. :-)

An alternative would be for me to include it without checking that it builds but it's not currently possible.

Thanks for the help.
